# Generated by Django 4.1.1 on 2022-10-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_modeltask_delete_modeltak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltask',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
